@startuml

Actor User
Boundary Login
Entity useAuth
Control AuthController
Database Database

User -> Login: username and password
Login -> AuthController: Verify user
AuthController -> Database: Verify user
AuthController <-- Database: User's info

alt User's information is correct 
  Login <-- AuthController: Username,\nrefresh token (httpOnly cookie), \naccess token, \nand roles
  Login -> useAuth: Set Username, \nrefresh token (httpOnly cookie), \naccess token, \nand roles into useContext
  User <-- Login: Redirect to Home page
else
  Login <-- AuthController: Return 401
  User <-- Login: Show error message
end


@endyml